// Arabic texts for this part of the site: English text -> Arabic text.
// First draft written by Claude, to be reviewed by a native Arabic speaker before launch.
// Contact and demo page.
const ar = {
  'Contact and Book a Demo': 'التواصل وحجز عرض توضيحي',
  'Talk to sales, book a demo, become a partner or get support.': 'تحدّث مع فريق المبيعات، أو احجز عرضًا توضيحيًا، أو كن شريكًا، أو احصل على الدعم.',
  'Contact': 'تواصل معنا',
  'Book a demo or ask us anything.': 'احجز عرضًا توضيحيًا أو اسألنا عن أي شيء.',
  'A demo is a 30-minute video call. We build a shop from your description while you watch, then answer your questions about plans, selling abroad or moving from another platform.': 'العرض التوضيحي مكالمة فيديو مدتها 30 دقيقة. نبني متجرًا من وصفك أمام عينيك، ثم نجيب عن أسئلتك حول الخطط والبيع في الخارج أو الانتقال من منصة أخرى.',
  'Sales and partners': 'المبيعات والشركاء',
  'Help with your shop': 'مساعدة بخصوص متجرك',
  'or the': 'أو',
  'help centre': 'مركز المساعدة',
  'What can we help with?': 'كيف يمكننا مساعدتك؟',
  'Sales question': 'سؤال عن المبيعات',
  'Support': 'الدعم',
  'Book my demo': 'احجز عرضي التوضيحي',
  'Send to sales': 'أرسل إلى المبيعات',
  'Talk to us': 'تحدّث معنا',
  'Send to support': 'أرسل إلى الدعم',
  'Anything you’d like us to cover? (optional)': 'هل هناك ما تودّ أن نتناوله؟ (اختياري)',
  'Your question': 'سؤالك',
  'Tell us about the shops you run': 'أخبرنا عن المتاجر التي تديرها',
  'What’s happening?': 'ماذا يحدث؟',
  'e.g. We sell in India and want to start shipping to the UAE': 'مثال: نبيع في الهند ونريد البدء بالشحن إلى الإمارات',
  'e.g. Can you build our storefront for us?': 'مثال: هل يمكنكم بناء واجهة متجرنا نيابةً عنا؟',
  'e.g. We run 40 shops for clients in Germany and want them under our brand': 'مثال: ندير 40 متجرًا لعملاء في ألمانيا ونريدها تحت علامتنا التجارية',
  'e.g. My courier tracking numbers aren’t showing on orders': 'مثال: أرقام تتبع شركة الشحن لا تظهر في الطلبات',
  'Your name': 'اسمك',
  'e.g. Priya Sharma': 'مثال: Priya Sharma',
  'Work email': 'البريد الإلكتروني للعمل',
  'you@shop.com': 'you@shop.com',
  'Shop or company (optional)': 'المتجر أو الشركة (اختياري)',
  'e.g. {store}': 'مثال: {store}',
  'Country': 'الدولة',
  'Choose a country': 'اختر دولة',
  'Germany': 'ألمانيا',
  'United States': 'الولايات المتحدة',
  'United Kingdom': 'المملكة المتحدة',
  'United Arab Emirates': 'الإمارات العربية المتحدة',
  'France': 'فرنسا',
  'Netherlands': 'هولندا',
  'Other': 'أخرى',
  'Enter your name.': 'أدخل اسمك.',
  'Enter a full email address, like you@shop.com.': 'أدخل عنوان بريد إلكتروني كاملًا، مثل you@shop.com.',
  'Tell us a little about what you need.': 'أخبرنا قليلًا عمّا تحتاج إليه.',
  'Thanks, {name}.': 'شكرًا، {name}.',
  'Thanks, we’ve got it.': 'شكرًا، وصلتنا رسالتك.',
  'We’ll email {email} with times for your demo.': 'سنراسلك على {email} بمواعيد العرض التوضيحي.',
  'Our support team will reply to {email}. If it’s about a live order, include the order number when we write back.': 'سيردّ فريق الدعم على {email}. إذا كان الأمر يخص طلبًا قائمًا، فأرفق رقم الطلب عند الرد علينا.',
  'We’ll reply to {email} from sales@dripfunnel.com.': 'سنردّ على {email} من sales@dripfunnel.com.',
  'Send another message': 'إرسال رسالة أخرى',
  'We use these details only to reply to you. See our': 'نستخدم هذه البيانات للرد عليك فقط. اطّلع على',
};

export default ar;
