// Arabic texts for this part of the site: English text -> Arabic text.
// First draft written by Claude, to be reviewed by a native Arabic speaker before launch.
// Texts of the Features page (components/pages/Features.jsx, content/features-data.js).
const ar = {
  // Page
  'Features': 'المزايا',
  'Everything a shop needs. Nothing to bolt on.': 'كل ما يحتاجه المتجر. دون أي إضافات خارجية.',
  '{count} features across ten parts of running a shop, all in one portal. Each one says which plan it starts on, and every plan has zero fees on your orders.':
    '{count} ميزة تغطي عشرة جوانب من إدارة المتجر، كلها في بوابة واحدة. تُبيّن كل ميزة الباقة التي تبدأ منها، وجميع الباقات بلا أي رسوم على طلباتك.',
  '{count} features': '{count} ميزة',
  '{count} on Starter (Free)': '{count} في Starter (مجانية)',
  '5 plans': '5 باقات',
  'Contents': 'المحتويات',
  'Index': 'الفهرس',
  'Every feature, by plan.': 'كل ميزة، حسب الباقة.',
  'The whole list on one page. Pick a plan to see what it includes; prices are on the {link}.':
    'القائمة كاملة في صفحة واحدة. اختر باقة لترى ما تشمله؛ الأسعار في {link}.',
  'pricing page': 'صفحة الأسعار',
  'Show features from': 'عرض المزايا من',
  'Try every feature for 10 days.': 'جرّب كل الميزات لمدة 10 أيام.',
  'New shops get everything in Business, no credit card. Then pick a plan or stay on Starter for free.':
    'تحصل المتاجر الجديدة على كل ما في Business دون بطاقة ائتمان. ثم اختر باقة أو ابقَ على Starter مجانًا.',
  'Start free': 'ابدأ مجانًا',
  'Compare plans': 'قارن الباقات',
  'Catalogue, orders and shipping, payments and tax, suppliers and selling abroad, all in one portal.':
    'الكتالوج والطلبات والشحن والمدفوعات والضرائب والموردون والبيع في الخارج، كلها في بوابة واحدة.',
  '{count} features across {areas} areas.': '{count} ميزة في {areas} مجالات.',
  '{count} of {total} features are included on {plan}. Greyed items start on a higher plan.':
    '{count} من أصل {total} ميزة مشمولة في {plan}. العناصر الباهتة تبدأ من باقة أعلى.',

  // Plans
  'All': 'الكل',
  'All plans': 'جميع الباقات',
  'Starter (Free)': 'Starter (مجانية)',
  'Growth': 'Growth',
  'Growth Pro': 'Growth Pro',
  'Business': 'Business',
  'Partner': 'Partner',

  // Shared words used in the sample panels and the sample shop
  'from {price} one-time': 'ابتداءً من {price} مرة واحدة',
  'M T W T F S S': 'ن ث ر خ ج س ح',
  'Live': 'مباشر',
  'Sent': 'أُرسل',
  'Sold out': 'نفد',
  'Active': 'نشط',
  'Staff': 'موظف',
  'Owner': 'المالك',
  'Manager': 'مدير',
  'Supplier': 'مورّد',
  'Everything': 'كل شيء',
  'Dubai': 'دبي',
  'Farhan': 'فرحان',
  'Mei': 'مي',
  'Ravi': 'رافي',
  'Aramex': 'Aramex',
  'Emirates Post': 'بريد الإمارات',
  'DHL': 'DHL',
  'Stripe': 'Stripe',
  'Tabby': 'Tabby',
  'Apple Pay': 'Apple Pay',
  'cash on delivery': 'الدفع عند الاستلام',
  'HS code, optional': 'رمز HS (اختياري)',
  'Compare-at price only if it was your real price': 'السعر المقارَن به فقط إذا كان سعرك الفعلي سابقًا',
  'VAT at 5%, included in every price': 'ضريبة القيمة المضافة 5% مشمولة في كل سعر',
  'Linen napkins, set of 4': 'مناديل كتان، طقم من 4',
  'Table runner': 'مفرش طاولة طويل',
  'Waffle hand towel': 'منشفة يد وافل',
  'Stonewashed throw': 'بطانية خفيفة مغسولة بالحجر',

  // 01 Storefront and AI
  'Storefront and AI': 'واجهة المتجر والذكاء الاصطناعي',
  'A store designed from a description': 'متجر يُصمَّم من وصف',
  'No themes, no templates. The AI designs the homepage, pages, menus, product pages and the look of all of them. You check, publish and can undo.':
    'لا قوالب جاهزة ولا سمات. يصمّم الذكاء الاصطناعي الصفحة الرئيسية والصفحات والقوائم وصفحات المنتجات ومظهرها جميعًا. أنت تراجع وتنشر ويمكنك التراجع.',
  'Every plan. On Starter and Growth the AI runs on your own key; from Growth Pro it is included.':
    'جميع الباقات. في Starter وGrowth يعمل الذكاء الاصطناعي بمفتاحك الخاص، ومن Growth Pro يكون مشمولًا.',
  'Describe a change': 'صف تغييرًا',
  'Plain words in, a draft out. One change at a time.': 'تكتب بكلمات بسيطة فتحصل على مسودة. تغيير واحد في كل مرة.',
  'Before and after preview': 'معاينة قبل وبعد',
  'Desktop, tablet and phone, side by side.': 'الحاسوب واللوحي والهاتف جنبًا إلى جنب.',
  'Approve and publish': 'وافق وانشر',
  'Nothing reaches shoppers until you press approve. Publishes in about a minute.':
    'لا يصل شيء إلى المتسوّقين حتى تضغط على الموافقة. يتم النشر خلال دقيقة تقريبًا.',
  'Version history and undo': 'سجل الإصدارات والتراجع',
  '7 days on Starter, 30 on Growth, 90 on Growth Pro, 1 year on Business.':
    '7 أيام في Starter، و30 في Growth، و90 في Growth Pro، وسنة واحدة في Business.',
  'AI included': 'الذكاء الاصطناعي مشمول',
  'A monthly allowance with no key to connect. Larger on Business.': 'رصيد شهري دون حاجة إلى ربط مفتاح. أكبر في Business.',
  'Your own AI key': 'مفتاح الذكاء الاصطناعي الخاص بك',
  'OpenAI or Anthropic. Paste it once in Settings.': 'OpenAI أو Anthropic. الصقه مرة واحدة في الإعدادات.',
  'Your own domain': 'نطاقك الخاص',
  'Connect a domain you already own: add one DNS record, we handle the certificate.':
    'اربط نطاقًا تملكه بالفعل: أضف سجل DNS واحدًا ونحن نتولى الشهادة.',
  'Remove “Powered by DripFunnel”': 'إزالة عبارة «Powered by DripFunnel»',
  'Your shop, your name only.': 'متجرك، واسمك وحده.',
  'Bandwidth that grows': 'سعة نقل بيانات تنمو معك',
  '1 GB on Starter to 200 GB on Business. Buy more on Business.': 'من 1 جيجابايت في Starter إلى 200 جيجابايت في Business. اشترِ المزيد في Business.',
  'We build it for you': 'نبنيه لك',
  'Optional one-time service: {setup}.': 'خدمة اختيارية لمرة واحدة: {setup}.',
  'Storefront · draft': 'واجهة المتجر · مسودة',
  'v14 · not live': 'الإصدار 14 · غير منشور',
  'Homepage': 'الصفحة الرئيسية',
  'Bestsellers first, new hero': 'الأكثر مبيعًا أولًا، وبانر رئيسي جديد',
  'Changed': 'تم تغييره',
  'Draft': 'مسودة',
  'Menu': 'القائمة',
  'Shop · Our story · Help': 'المتجر · قصتنا · المساعدة',
  'Products and prices': 'المنتجات والأسعار',
  'Not touched': 'لم يُمسّ',
  'Checkout': 'إتمام الشراء',
  'Approve & publish · Discard · History': 'موافقة ونشر · تجاهل · السجل',

  // 02 Catalogue
  'Catalogue': 'الكتالوج',
  'A catalogue that handles the detail': 'كتالوج يهتم بالتفاصيل',
  'Add a product once and sell every size and colour of it, with the content shoppers need to decide.':
    'أضف المنتج مرة واحدة وبع كل مقاساته وألوانه، مع المحتوى الذي يحتاجه المتسوّقون لاتخاذ قرارهم.',
  'Starter: 10 products. Growth: 100. Growth Pro: 5,000. Business: unlimited.':
    'في Starter 10 منتجات، وفي Growth 100، وفي Growth Pro 5,000، وفي Business عدد غير محدود.',
  'Versions': 'الخيارات',
  'Every size × colour with its own price, stock, photos and code. Up to 250 per product on Business.':
    'كل مقاس × لون بسعره ومخزونه وصوره ورمزه. حتى 250 لكل منتج في Business.',
  'Photos': 'الصور',
  '3 per product on Starter, up to 50 on Business.': '3 لكل منتج في Starter، وحتى 50 في Business.',
  'Product video': 'فيديو المنتج',
  'One video per product, shown with the photos.': 'فيديو واحد لكل منتج، يُعرض مع الصور.',
  'A+ content': 'محتوى A+',
  'Rich modules below the fold: comparison tables, feature rows, story sections.':
    'أقسام غنية أسفل الصفحة: جداول مقارنة وصفوف مزايا وأقسام قصصية.',
  'Size charts': 'جداول المقاسات',
  'Build once, attach to many products. 1 on Starter, 25 on Growth Pro.': 'أنشئه مرة واحدة واربطه بعدة منتجات. 1 في Starter و25 في Growth Pro.',
  'Collections': 'المجموعات',
  'Manual or by rule. 3 on Starter, unlimited from Growth Pro.': 'يدوية أو حسب قاعدة. 3 في Starter وغير محدودة من Growth Pro.',
  'Filters and internal tags': 'عوامل التصفية والوسوم الداخلية',
  'Shoppers filter by what matters; tags stay private.': 'يصفّي المتسوّقون حسب ما يهمهم، وتبقى الوسوم خاصة.',
  'Menus': 'القوائم',
  'Header and footer menus, or let the AI arrange them.': 'قوائم الرأس والتذييل، أو دع الذكاء الاصطناعي يرتبها.',
  'Specifications and highlights': 'المواصفات وأبرز النقاط',
  'Structured facts shoppers compare on.': 'حقائق منظمة يقارن المتسوّقون على أساسها.',
  'Badges': 'الشارات',
  'New, bestseller, low stock, your own.': 'جديد، الأكثر مبيعًا، مخزون منخفض، أو شاراتك الخاصة.',
  'FAQs and related products': 'الأسئلة الشائعة والمنتجات ذات الصلة',
  'Answer the question on the page; suggest the next thing.': 'أجب عن السؤال في الصفحة نفسها، واقترح المنتج التالي.',
  'AI descriptions': 'أوصاف بالذكاء الاصطناعي',
  'Written in your tone from a few facts.': 'تُكتب بأسلوبك انطلاقًا من بعض المعلومات.',
  'AI translations': 'ترجمات بالذكاء الاصطناعي',
  'Every language your markets need, from one source text.': 'كل لغة تحتاجها أسواقك، من نص أصلي واحد.',
  'Import from a spreadsheet': 'الاستيراد من جدول بيانات',
  'Match columns once, pause and resume, see what failed and why.': 'طابق الأعمدة مرة واحدة، وأوقف واستأنف، واعرف ما فشل ولماذا.',
  'Bring products from Shopify': 'انقل منتجاتك من Shopify',
  'Products, versions, photos and collections come across.': 'تنتقل المنتجات والخيارات والصور والمجموعات.',
  'Export': 'التصدير',
  'CSV of products, stock or orders, ready for your accountant.': 'ملف CSV للمنتجات أو المخزون أو الطلبات، جاهز لمحاسبك.',
  'Stock history': 'سجل المخزون',
  'Every change to every version, who and when.': 'كل تغيير على كل خيار، ومن أجراه ومتى.',
  'Bulk edit': 'التعديل الجماعي',
  'Select many, change price, stock, collections or status at once.': 'حدّد عدة منتجات وغيّر السعر أو المخزون أو المجموعات أو الحالة دفعة واحدة.',
  'Legal and safety details': 'التفاصيل القانونية وتفاصيل السلامة',
  'Country of origin, warnings, {code}, MRP or MSRP. Never behind a paywall.':
    'بلد المنشأ والتحذيرات و{code} وسعر البيع المقترح. لا تكون أبدًا خلف جدار دفع.',
  'Compare-at price': 'السعر المقارَن به',
  '{note}.': '{note}.',
  '8 versions · 3 languages': '8 خيارات · 3 لغات',
  'S · Natural': 'S · طبيعي',
  'In stock at {city}': 'متوفر في {city}',
  '24 left': 'تبقّى 24',
  'M · Natural': 'M · طبيعي',
  '18 left': 'تبقّى 18',
  'L · Indigo': 'L · نيلي',
  'Supplier stock': 'مخزون المورّد',
  '3 left': 'تبقّى 3',
  'XL · Indigo': 'XL · نيلي',
  'A+ content · Product video · Size chart · {code}': 'محتوى A+ · فيديو المنتج · جدول المقاسات · {code}',

  // 03 Orders and shipping
  'Orders and shipping': 'الطلبات والشحن',
  'Orders, shipping and returns in one place': 'الطلبات والشحن والمرتجعات في مكان واحد',
  'See what to ship first, send it with your courier, and handle returns without a spreadsheet.':
    'اعرف ما يجب شحنه أولًا، وأرسله مع شركة الشحن، وتعامل مع المرتجعات دون جداول بيانات.',
  'Every plan has unlimited orders. Live courier rates from Growth Pro. 10 stock locations on Business.':
    'جميع الباقات بلا حد للطلبات. أسعار شركات الشحن المباشرة من Growth Pro. 10 مواقع مخزون في Business.',
  'Order list and filters': 'قائمة الطلبات وعوامل التصفية',
  'To ship, unpaid, returns, by market, by supplier.': 'للشحن، غير مدفوعة، مرتجعات، حسب السوق، حسب المورّد.',
  'Ship with your courier': 'اشحن مع شركة الشحن الخاصة بك',
  '{couriers}. Tracking goes to the shopper automatically.': '{couriers}. يصل رقم التتبع إلى المتسوّق تلقائيًا.',
  'Live courier rates at checkout': 'أسعار الشحن المباشرة عند إتمام الشراء',
  'Shoppers see the real price before they pay.': 'يرى المتسوّقون السعر الحقيقي قبل أن يدفعوا.',
  'Partial shipping': 'الشحن الجزئي',
  'Send what you have now and the rest later.': 'أرسل ما لديك الآن والباقي لاحقًا.',
  'Refunds': 'المبالغ المستردة',
  'All or part of an order, back to the original payment.': 'كامل الطلب أو جزء منه، إلى وسيلة الدفع الأصلية.',
  'Returns': 'المرتجعات',
  'Request, approve, receive, refund. Each supplier handles their own items; you can override.':
    'طلب وموافقة واستلام واسترداد. يتولى كل مورّد منتجاته، ويمكنك التدخل عند الحاجة.',
  'Cancellations': 'الإلغاءات',
  'Before shipping, with stock put back.': 'قبل الشحن، مع إعادة المخزون.',
  'Invoices, packing slips and labels': 'الفواتير وقوائم التعبئة وملصقات الشحن',
  'Print one or many, with the right tax wording for the market.': 'اطبع واحدة أو عدة منها، بصياغة الضريبة الصحيحة للسوق.',
  'Delivery charges': 'رسوم التوصيل',
  'Free, flat, by weight, or free above a threshold.': 'مجانية أو ثابتة أو حسب الوزن، أو مجانية فوق حد معيّن.',
  'Delivery-area lists': 'قوائم مناطق التوصيل',
  'Postcodes or regions you do and don’t deliver to.': 'الرموز البريدية أو المناطق التي توصّل إليها والتي لا توصّل إليها.',
  'Stock locations': 'مواقع المخزون',
  '1 on Starter, 5 on Growth Pro, 10 on Business.': '1 في Starter، و5 في Growth Pro، و10 في Business.',
  'Customers and groups': 'العملاء والمجموعات',
  'Profiles, order history, notes and groups for offers.': 'الملفات الشخصية وسجل الطلبات والملاحظات ومجموعات للعروض.',
  'Email the customer': 'راسل العميل بالبريد الإلكتروني',
  'From the order, with the order details filled in.': 'من الطلب نفسه، مع تعبئة تفاصيل الطلب تلقائيًا.',
  'Order exports': 'تصدير الطلبات',
  'CSV by date range, market or status.': 'ملف CSV حسب الفترة أو السوق أو الحالة.',
  'Order #1042': 'الطلب #1042',
  'Paid · 2 items': 'مدفوع · منتجان',
  'Qty 1': 'الكمية 1',
  'Packed': 'تمت التعبئة',
  'Qty 2': 'الكمية 2',
  'To ship': 'للشحن',
  'Courier': 'شركة الشحن',
  '{courier} · tracking added': '{courier} · تمت إضافة رقم التتبع',
  'Shipped': 'تم الشحن',
  'Print invoice · Packing slip · Label · Refund': 'طباعة الفاتورة · قائمة التعبئة · الملصق · استرداد',

  // 04 Payments and tax
  'Payments and tax': 'المدفوعات والضرائب',
  'Get paid the way your shoppers pay': 'احصل على أموالك بالطريقة التي يدفع بها متسوّقوك',
  'Local payment methods, local tax rules and zero DripFunnel fees on every order.':
    'وسائل دفع محلية وقواعد ضريبية محلية وبلا أي رسوم من DripFunnel على كل طلب.',
  'Zero fees on every plan. 1 gateway on Starter, 2 on Growth, all from Growth Pro.':
    'بلا رسوم في جميع الباقات. بوابة دفع واحدة في Starter، واثنتان في Growth، وجميعها من Growth Pro.',
  'Zero fees on your orders': 'بلا رسوم على طلباتك',
  'We never take a cut of your sales. You pay only your provider.': 'لا نقتطع أي نسبة من مبيعاتك أبدًا. تدفع لمزوّدك فقط.',
  'Payment gateways': 'بوابات الدفع',
  '{methods}. Connect in minutes.': '{methods}. اربطها في دقائق.',
  'Cash on delivery and bank transfer': 'الدفع عند الاستلام والتحويل المصرفي',
  'For markets where cards are not the norm.': 'للأسواق التي لا تنتشر فيها البطاقات.',
  'Local tax worked out': 'حساب الضريبة المحلية',
  'Tax-inclusive or exclusive prices': 'أسعار شاملة الضريبة أو غير شاملة',
  'Follows the rule of each market automatically.': 'تتبع قاعدة كل سوق تلقائيًا.',
  'Tax report': 'تقرير الضرائب',
  'What you owe, by market and rate.': 'ما يترتب عليك، حسب السوق والنسبة.',
  'Shopper invoices': 'فواتير المتسوّقين',
  'Numbered, with the tax detail each country needs.': 'مرقّمة، وبتفاصيل الضريبة التي تحتاجها كل دولة.',
  'Payments': 'المدفوعات',
  'United Arab Emirates': 'الإمارات العربية المتحدة',
  'Connected': 'متصل',
  'Available': 'متاح',
  'DripFunnel fee: {amount} on every order': 'رسوم DripFunnel: {amount} على كل طلب',

  // 05 Offers and carts
  'Offers and carts': 'العروض والسلال',
  'Offers that bring people back': 'عروض تعيد الناس إلى متجرك',
  'Run the offer you have in mind and see whether it worked. Remind shoppers who left something behind.':
    'أطلق العرض الذي تفكر فيه واعرف هل نجح. ذكّر المتسوّقين الذين تركوا شيئًا في السلة.',
  '3 live offers on Starter and Growth. Unlimited offers and automatic reminders from Growth Pro.':
    '3 عروض مباشرة في Starter وGrowth. عروض غير محدودة وتذكيرات تلقائية من Growth Pro.',
  'Discount codes': 'رموز الخصم',
  'Percent off, fixed amount or free delivery.': 'نسبة خصم أو مبلغ ثابت أو توصيل مجاني.',
  'Automatic offers': 'عروض تلقائية',
  'No code needed; applied when the rule is met.': 'لا حاجة إلى رمز؛ يُطبَّق العرض عند تحقق الشرط.',
  'Buy X get Y': 'اشترِ X واحصل على Y',
  'Buy 2 get 1, mix and match, cheapest free.': 'اشترِ 2 واحصل على 1، امزج وطابق، الأرخص مجاني.',
  'Minimum spend and quantity': 'حد أدنى للإنفاق والكمية',
  'Set the bar the cart must clear.': 'حدّد الحد الذي يجب أن تتجاوزه السلة.',
  'Single-use codes': 'رموز للاستخدام مرة واحدة',
  'One per shopper, generated in bulk or sent in a reminder.': 'رمز لكل متسوّق، يُنشأ بالجملة أو يُرسل في تذكير.',
  'Customer-group offers': 'عروض لمجموعات العملاء',
  'Trade, VIP, first order, your own groups.': 'تجّار، كبار العملاء، الطلب الأول، أو مجموعاتك الخاصة.',
  'Tiered offers': 'عروض متدرجة',
  'Spend more, save more.': 'أنفق أكثر، ووفّر أكثر.',
  'Schedules and stacking rules': 'الجداول الزمنية وقواعد الجمع بين العروض',
  'Start and end dates, and which offers may combine.': 'تواريخ البدء والانتهاء، وأي العروض يمكن الجمع بينها.',
  'Offer results': 'نتائج العروض',
  'Orders, revenue and discount given, per offer.': 'الطلبات والإيرادات والخصم الممنوح، لكل عرض.',
  'Abandoned-cart reminders': 'تذكيرات السلات المتروكة',
  'One you send yourself on Starter; up to 3 sent automatically from Growth Pro.':
    'تذكير واحد ترسله بنفسك في Starter، وحتى 3 تذكيرات ترسَل تلقائيًا من Growth Pro.',
  'Discount in the last reminder': 'خصم في آخر تذكير',
  'A single-use code, only if the first two didn’t work.': 'رمز للاستخدام مرة واحدة، فقط إذا لم ينجح أول تذكيرين.',
  'Regional wording': 'صياغة حسب المنطقة',
  'Coupon or voucher, shipping or delivery, by market.': 'كوبون أو قسيمة، شحن أو توصيل، حسب السوق.',
  'Buy 2, get 1 free': 'اشترِ 2 واحصل على 1 مجانًا',
  'Automatic offer · live': 'عرض تلقائي · مباشر',
  'Who': 'الفئة',
  'Everyone': 'الجميع',
  'Reminder 1': 'التذكير 1',
  '1 hour after they leave': 'بعد ساعة من مغادرتهم',
  'Reminder 2': 'التذكير 2',
  '1 day after': 'بعد يوم',
  'Reminder 3': 'التذكير 3',
  '3 days after, with a single-use code': 'بعد 3 أيام، مع رمز للاستخدام مرة واحدة',
  'Scheduled': 'مجدول',
  'Code': 'رمز',

  // 06 Selling abroad
  'Selling abroad': 'البيع في الخارج',
  'Sell in many countries from one shop': 'بع في دول كثيرة من متجر واحد',
  'Add a market and your shop shows the right currency, language, tax and payment methods there.':
    'أضف سوقًا فيعرض متجرك هناك العملة واللغة والضريبة ووسائل الدفع المناسبة.',
  'Home market on Starter and Growth. 2 markets on Growth Pro, 10 on Business.':
    'السوق المحلي في Starter وGrowth. سوقان في Growth Pro، و10 في Business.',
  'Markets': 'الأسواق',
  'Each with its own currency, languages, tax and couriers.': 'لكل سوق عملته ولغاته وضريبته وشركات الشحن الخاصة به.',
  'Currencies': 'العملات',
  'Automatic conversion, or set prices yourself.': 'تحويل تلقائي، أو حدّد الأسعار بنفسك.',
  'Languages': 'اللغات',
  'Shop, emails and invoices in the shopper’s language.': 'المتجر ورسائل البريد والفواتير بلغة المتسوّق.',
  'Price adjustment per market': 'تعديل السعر لكل سوق',
  '+10% for one country, rounded nicely.': '+10% لدولة واحدة، مع تقريب مناسب.',
  'Fixed prices per market': 'أسعار ثابتة لكل سوق',
  'Exact local prices, not conversions.': 'أسعار محلية دقيقة، لا مجرد تحويلات.',
  'Duties and import taxes at checkout': 'الرسوم الجمركية وضرائب الاستيراد عند إتمام الشراء',
  'Shoppers pay once, nothing at the door.': 'يدفع المتسوّقون مرة واحدة، ولا شيء عند الباب.',
  'Own domain per market': 'نطاق خاص لكل سوق',
  'shop.de, shop.in, shop.com.': 'shop.de وshop.in وshop.com.',
  'Local payment methods': 'وسائل دفع محلية',
  'Klarna in Germany, PhonePe in India, PayPal in the US.': 'Klarna في ألمانيا، وPhonePe في الهند، وPayPal في الولايات المتحدة.',
  'Local couriers': 'شركات شحن محلية',
  'DHL, Shiprocket, USPS and more.': 'DHL وShiprocket وUSPS وغيرها.',
  'Local rules built in': 'قواعد محلية مدمجة',
  'VAT-inclusive prices, 30-day lowest price in the EU, MRP in India, HSN codes.':
    'أسعار شاملة ضريبة القيمة المضافة، وأقل سعر في آخر 30 يومًا في الاتحاد الأوروبي، وسعر MRP في الهند، ورموز HSN.',
  '5 live': '5 مباشرة',
  'India': 'الهند',
  'INR · Hindi, English': 'INR · الهندية، الإنجليزية',
  'GST incl.': 'شامل ضريبة GST',
  'Germany': 'ألمانيا',
  'EUR · German': 'EUR · الألمانية',
  'VAT 19% incl.': 'شامل ضريبة القيمة المضافة 19%',
  'United States': 'الولايات المتحدة',
  'USD · English': 'USD · الإنجليزية',
  'Sales tax excl.': 'غير شامل ضريبة المبيعات',
  'AED · Arabic, English': 'AED · العربية، الإنجليزية',
  'VAT 5% incl.': 'شامل ضريبة القيمة المضافة 5%',
  'United Kingdom': 'المملكة المتحدة',
  'GBP · English': 'GBP · الإنجليزية',
  'VAT 20% incl.': 'شامل ضريبة القيمة المضافة 20%',
  'Duties at checkout': 'الرسوم عند إتمام الشراء',

  // 07 Suppliers
  'Suppliers': 'الموردون',
  'Suppliers who manage their own shelf': 'موردون يديرون رفّهم بأنفسهم',
  'Let suppliers keep their own products and stock up to date, and even pack their own orders, under your rules.':
    'دع الموردين يحدّثون منتجاتهم ومخزونهم بأنفسهم، بل ويعبّئون طلباتهم، وفق قواعدك.',
  'Business and Partner. Unlimited suppliers; their users don’t count towards your staff.':
    'Business وPartner. موردون بلا حد؛ ومستخدموهم لا يُحتسبون ضمن موظفيك.',
  'Invite suppliers': 'دعوة الموردين',
  'By email. The invitation creates their business and first user.': 'عبر البريد الإلكتروني. تُنشئ الدعوة نشاطهم التجاري ومستخدمهم الأول.',
  'Three access levels': 'ثلاثة مستويات وصول',
  'Stock only; products and stock; or also packing their own orders.': 'المخزون فقط؛ أو المنتجات والمخزون؛ أو أيضًا تعبئة طلباتهم.',
  'Approval before going live': 'موافقة قبل النشر',
  'Optional. Review, approve or send back with a reason.': 'اختيارية. راجع ووافق أو أعد المنتج مع ذكر السبب.',
  'Approval for edits': 'موافقة على التعديلات',
  'Decide whether an edit to a live product needs a second look.': 'قرّر هل يحتاج تعديل منتج منشور إلى مراجعة إضافية.',
  'Suppliers see only their own': 'يرى كل مورّد ما يخصه فقط',
  'Their products, their order lines, the delivery address. Never the order total or other suppliers.':
    'منتجاتهم وبنود طلباتهم وعنوان التوصيل. ولا يرون أبدًا إجمالي الطلب ولا الموردين الآخرين.',
  'Shared record': 'سجل مشترك',
  'You can edit a supplier’s product and they see the change. Only price is yours alone.':
    'يمكنك تعديل منتج المورّد ويرى هو التغيير. السعر وحده يبقى لك.',
  'Suppliers pack their own orders': 'الموردون يعبّئون طلباتهم بأنفسهم',
  'Ship to your warehouse or straight to the shopper, your choice per supplier.': 'الشحن إلى مستودعك أو مباشرة إلى المتسوّق، وخيارك لكل مورّد.',
  'Supplier returns': 'مرتجعات الموردين',
  'Each supplier handles their own items; you can override.': 'يتولى كل مورّد منتجاته، ويمكنك التدخل عند الحاجة.',
  'Supplier report': 'تقرير الموردين',
  'What each supplier sold, by period.': 'ما باعه كل مورّد، حسب الفترة.',
  'Suspend or remove': 'تعليق أو إزالة',
  'Their products stay in the catalogue, paused, until you decide.': 'تبقى منتجاتهم في الكتالوج موقوفة مؤقتًا إلى أن تقرّر.',
  '2 active · 1 to approve': '2 نشطان · 1 بانتظار الموافقة',
  'Loom House': 'Loom House',
  'Products and stock': 'المنتجات والمخزون',
  '12 products': '12 منتجًا',
  'Indigo Mills': 'Indigo Mills',
  'Also packs own orders': 'يعبّئ طلباته أيضًا',
  '31 products': '31 منتجًا',
  'New product': 'منتج جديد',
  'From Loom House, this morning': 'من Loom House، هذا الصباح',
  'To approve': 'بانتظار الموافقة',
  'Approve · Send back with a reason': 'موافقة · إعادة مع ذكر السبب',

  // 08 Team and security
  'Team and security': 'الفريق والأمان',
  'Your team, with the right keys': 'فريقك، بالصلاحيات المناسبة',
  'Each person sees only what their job needs, and every account is protected.': 'يرى كل شخص ما تتطلبه مهمته فقط، وكل حساب محمي.',
  'Owner only on Starter. 2 staff on Growth, 5 on Growth Pro, 15 on Business.':
    'المالك فقط في Starter. موظفان في Growth، و5 في Growth Pro، و15 في Business.',
  'Owner, Manager and Staff roles': 'أدوار المالك والمدير والموظف',
  'Owner runs everything; Manager runs catalogue and orders; Staff handle orders and customers.':
    'المالك يدير كل شيء، والمدير يدير الكتالوج والطلبات، والموظفون يتولون الطلبات والعملاء.',
  'Manager role': 'دور المدير',
  'Day-to-day running without billing or settings.': 'التشغيل اليومي دون الفوترة أو الإعدادات.',
  'Invitations': 'الدعوات',
  'Email invites that expire after 7 days. Resend or revoke any time.': 'دعوات بالبريد الإلكتروني تنتهي بعد 7 أيام. أعد إرسالها أو ألغها في أي وقت.',
  'View-only where it matters': 'عرض فقط حيث يلزم',
  'Staff can see offers and collections but not change them.': 'يستطيع الموظفون رؤية العروض والمجموعات دون تغييرها.',
  'Two-step sign-in': 'تسجيل دخول بخطوتين',
  'Authenticator app or email code, with backup codes.': 'تطبيق مصادقة أو رمز بريد إلكتروني، مع رموز احتياطية.',
  'Activity in the stock history': 'النشاط في سجل المخزون',
  'Who changed what, and when.': 'من غيّر ماذا، ومتى.',
  'My profile': 'ملفي الشخصي',
  'Name, email, password, appearance and time zone.': 'الاسم والبريد الإلكتروني وكلمة المرور والمظهر والمنطقة الزمنية.',
  'Support access switch': 'مفتاح وصول الدعم',
  'Decide whether support may look at your store, and for how long.': 'قرّر هل يجوز للدعم الاطلاع على متجرك، ولكم من الوقت.',
  'People': 'الأشخاص',
  '3 staff · 2 suppliers': '3 موظفين · موردان',
  'Catalogue, orders, offers': 'الكتالوج والطلبات والعروض',
  'Orders and customers': 'الطلبات والعملاء',
  'Supplier · products and stock': 'مورّد · المنتجات والمخزون',

  // 09 Reports
  'Reports': 'التقارير',
  'Reports that answer the obvious questions': 'تقارير تجيب عن الأسئلة البديهية',
  'What came in, what sold, where it went and how much tax you owe.': 'ما الذي دخل، وما الذي بِيع، وإلى أين ذهب، وكم تدين من ضرائب.',
  'Home numbers on every plan. The 4 reports from Growth. Export from Growth Pro. Custom on Business.':
    'أرقام الصفحة الرئيسية في كل باقة. التقارير الأربعة من Growth. التصدير من Growth Pro. تقارير مخصصة في Business.',
  'Home numbers': 'أرقام الصفحة الرئيسية',
  'Takings, orders and visitors today, on the first screen.': 'إيرادات اليوم والطلبات والزوار، على الشاشة الأولى.',
  'Takings': 'الإيرادات',
  'By day, week or month, with refunds taken off.': 'حسب اليوم أو الأسبوع أو الشهر، بعد خصم المبالغ المستردة.',
  'What sold': 'ما الذي بِيع',
  'Products and versions, so you know what to restock.': 'المنتجات والخيارات، لتعرف ما يجب إعادة توفيره.',
  'Where orders come from, in each currency.': 'من أين تأتي الطلبات، بكل عملة.',
  'Tax': 'الضريبة',
  'Collected by market and rate, ready to file.': 'المحصَّلة حسب السوق والنسبة، جاهزة للتقديم.',
  'Sales per supplier for settling up.': 'المبيعات لكل مورّد لأجل التسوية.',
  'Export any report': 'تصدير أي تقرير',
  'CSV for your spreadsheet or accountant.': 'ملف CSV لجدول بياناتك أو لمحاسبك.',
  'Custom reports': 'تقارير مخصصة',
  'Pick the columns, filters and period, and save it.': 'اختر الأعمدة وعوامل التصفية والفترة، ثم احفظ التقرير.',
  'Takings · last 7 days': 'الإيرادات · آخر 7 أيام',
  'Sample data': 'بيانات تجريبية',

  // 10 Plans and billing
  'Plans and billing': 'الباقات والفوترة',
  'Plans that don’t punish you for growing': 'باقات لا تعاقبك على نموّك',
  'Start free, try everything, and change plans without losing work.': 'ابدأ مجانًا، وجرّب كل شيء، وغيّر الباقة دون أن تخسر عملك.',
  'Every plan. Nothing you made is ever deleted when you move down.': 'جميع الباقات. لا يُحذف أي شيء أنشأته عند الانتقال إلى باقة أدنى.',
  'Starter, free forever': 'Starter، مجانية دائمًا',
  'A real shop with 10 products, for as long as you like.': 'متجر حقيقي بـ 10 منتجات، للمدة التي تريدها.',
  '10-day trial of Business': 'تجربة Business لمدة 10 أيام',
  'Every feature, no credit card. We remind you before it ends.': 'كل الميزات دون بطاقة ائتمان. نذكّرك قبل انتهائها.',
  'Upgrade now, downgrade later': 'رقِّ الآن، وخفّض لاحقًا',
  'Upgrades start straight away; downgrades at the end of the period.': 'تبدأ الترقية فورًا؛ ويبدأ التخفيض في نهاية الفترة.',
  'Choose what to keep': 'اختر ما تحتفظ به',
  'Over a limit after a downgrade? Pick what stays live. The rest is paused, not deleted.':
    'تجاوزت الحد بعد التخفيض؟ اختر ما يبقى منشورًا. والباقي يُوقَف مؤقتًا ولا يُحذف.',
  'Monthly or yearly': 'شهريًا أو سنويًا',
  'Yearly costs half the monthly price.': 'الاشتراك السنوي بنصف السعر الشهري.',
  'Invoices': 'الفواتير',
  'Downloadable, with your business details and tax ID.': 'قابلة للتنزيل، مع بيانات نشاطك ورقمك الضريبي.',
  'Past due, not locked out': 'متأخر السداد دون إيقاف الحساب',
  'If a payment fails you can still see everything; changes wait until it’s fixed.': 'إذا فشلت عملية دفع تبقى ترى كل شيء؛ وتنتظر التغييرات حتى تُحلّ المشكلة.',
  'Cancel any time': 'ألغِ في أي وقت',
  'From Billing, with a clear note on what happens to the shop and domain.': 'من صفحة الفوترة، مع توضيح لما يحدث للمتجر والنطاق.',
  'Billing': 'الفوترة',
  'Growth Pro · yearly': 'Growth Pro · سنويًا',
  'Plan': 'الباقة',
  'Next invoice': 'الفاتورة التالية',
  '1 October 2027': '1 أكتوبر 2027',
  'Card': 'البطاقة',
  'Visa ending 4417': 'Visa تنتهي بـ 4417',
  'Trial': 'التجربة',
  'Ended · you chose Growth Pro': 'انتهت · اخترت Growth Pro',
  'Change plan · Download invoices · Cancel': 'تغيير الباقة · تنزيل الفواتير · إلغاء',
};

export default ar;
