// Arabic texts for the help centre: English text -> Arabic text.
// First draft written by Claude, to be reviewed by a native Arabic speaker before launch.
const ar = {
  // Index
  'Help Centre': 'مركز المساعدة',
  'Help centre': 'مركز المساعدة',
  'How-to articles and support for running your DripFunnel shop.': 'مقالات إرشادية ودعم لإدارة متجرك على DripFunnel.',
  '{title}. A how-to article in the DripFunnel Help Centre.': '{title}. مقال إرشادي في مركز مساعدة DripFunnel.',
  'How can we help?': 'كيف يمكننا مساعدتك؟',
  'Search help articles': 'ابحث في مقالات المساعدة',
  'Search, e.g. refund, size chart, GST': 'ابحث، مثل: استرداد، جدول المقاسات، ضريبة',
  '1 article for “{q}”': 'مقال واحد عن «{q}»',
  '{n} articles for “{q}”': '{n} مقالات عن «{q}»',
  'Nothing matches that yet. Try another word, or': 'لا توجد نتائج مطابقة حتى الآن. جرّب كلمة أخرى، أو',
  'ask our support team': 'اسأل فريق الدعم لدينا',
  'Still stuck?': 'ما زلت تواجه مشكلة؟',
  'Write to our support team. Paid plans also get chat from inside the portal.': 'راسل فريق الدعم لدينا. وتحصل الباقات المدفوعة أيضًا على محادثة من داخل البوابة.',
  'Contact support': 'تواصل مع الدعم',

  // Categories and their descriptions
  'Getting started': 'البدء',
  'Sign up, first products, going live': 'التسجيل، أول المنتجات، الإطلاق',
  Catalogue: 'الكتالوج',
  'Products, versions, collections, imports': 'المنتجات والنسخ والمجموعات والاستيراد',
  'Orders and shipping': 'الطلبات والشحن',
  'Shipping, tracking, returns, refunds': 'الشحن والتتبع والمرتجعات والمبالغ المستردة',
  'Payments and tax': 'المدفوعات والضرائب',
  'Payment methods, tax, invoices': 'طرق الدفع والضرائب والفواتير',
  'Storefront and AI': 'واجهة المتجر والذكاء الاصطناعي',
  'Describe, preview, publish, undo': 'الوصف والمعاينة والنشر والتراجع',
  'Selling abroad': 'البيع في الخارج',
  'Markets, currencies, languages, duties': 'الأسواق والعملات واللغات والرسوم الجمركية',
  'Team and suppliers': 'الفريق والموردون',
  'Staff roles, suppliers, approvals': 'أدوار الموظفين والموردون والموافقات',
  'Billing and plans': 'الفوترة والباقات',
  'Plans, invoices, upgrades, cancelling': 'الباقات والفواتير والترقية والإلغاء',

  // Articles
  'Set up your store in your first 10 minutes': 'جهّز متجرك في أول 10 دقائق',
  'Go live: what to check before you share your shop': 'الإطلاق: ما الذي تراجعه قبل مشاركة متجرك',
  'How the 10-day trial works': 'كيف تعمل الفترة التجريبية لمدة 10 أيام',
  'Add a product with sizes and colours': 'أضف منتجًا بمقاسات وألوان',
  'Import products from a spreadsheet': 'استورد المنتجات من جدول بيانات',
  'Bring your products from Shopify': 'انقل منتجاتك من Shopify',
  'Ship an order and add tracking': 'اشحن طلبًا وأضف رقم التتبع',
  'Refund all or part of an order': 'استرد كامل مبلغ الطلب أو جزءًا منه',
  'Print invoices, packing slips and labels': 'اطبع الفواتير وقوائم التعبئة والملصقات',
  'Connect a payment method': 'اربط طريقة دفع',
  'How tax is worked out in each country': 'كيف تُحسب الضريبة في كل بلد',
  'Offer cash on delivery': 'وفّر الدفع عند الاستلام',
  'Describe a change to your storefront': 'صِف تغييرًا في واجهة متجرك',
  'Go back to an earlier version': 'ارجع إلى نسخة سابقة',
  'Connect your own AI key': 'اربط مفتاح الذكاء الاصطناعي الخاص بك',
  'Add a market': 'أضف سوقًا',
  'Set prices per currency': 'حدّد الأسعار لكل عملة',
  'Charge duties at checkout': 'احتسب الرسوم الجمركية عند الدفع',
  'Invite staff and choose their role': 'ادعُ موظفين واختر دور كل منهم',
  'Invite a supplier': 'ادعُ موردًا',
  'Turn on approval for supplier products': 'فعّل الموافقة على منتجات الموردين',
  'Change your plan': 'غيّر باقتك',
  'Download your invoices': 'نزّل فواتيرك',
  'Cancel your subscription': 'ألغِ اشتراكك',

  // Article page
  Breadcrumb: 'مسار التنقل',
  'Updated 1 October 2026': 'آخر تحديث: 1 أكتوبر 2026',
  Everyone: 'الجميع',
  Owners: 'المالكون',
  'Owners, managers, staff': 'المالكون والمديرون والموظفون',
  'Owners on Business': 'المالكون على باقة Business',
  'Placeholder: a short line on what this article helps with.': 'نص مؤقت: سطر قصير عمّا يساعدك فيه هذا المقال.',
  'Good to know:': 'من المفيد أن تعرف:',
  'Placeholder: step-by-step instructions go here.': 'نص مؤقت: ستوضع هنا التعليمات خطوة بخطوة.',
  'Did this answer your question?': 'هل أجاب هذا المقال عن سؤالك؟',
  Yes: 'نعم',
  No: 'لا',
  'Thanks for telling us.': 'شكرًا لإخبارنا.',
  'Sorry about that. Contact support and we’ll help directly.': 'نأسف لذلك. تواصل مع الدعم وسنساعدك مباشرة.',
  'More in {category}': 'المزيد في {category}',
  'Need a person?': 'تحتاج إلى التحدث مع شخص؟',
  'Tell us your store name and what you were trying to do.': 'أخبرنا باسم متجرك وما كنت تحاول فعله.',

  // Article bodies
  'Only the store owner can change the storefront. Managers and staff can look but not publish.': 'يستطيع مالك المتجر وحده تغيير واجهة المتجر. يمكن للمديرين والموظفين الاطلاع دون النشر.',
  'In the portal, open Storefront.': 'في البوابة، افتح «واجهة المتجر».',
  'Under Describe a change, write what you want in plain words, for example “Make the menu simpler: Shop, Our story, Help”.':
    'تحت «صِف تغييرًا»، اكتب ما تريده بكلمات بسيطة، مثل «اجعل القائمة أبسط: المتجر، قصتنا، المساعدة».',
  'Wait for the draft. It shows what changed and what wasn’t touched.': 'انتظر ظهور المسودة. تعرض لك ما تغيّر وما لم يُمسّ.',
  'Check it on Desktop, Tablet and Phone.': 'راجعها على الحاسوب واللوحي والهاتف.',
  'Press Approve & publish, or Discard to throw the draft away.': 'اضغط «اعتماد ونشر»، أو «تجاهل» لحذف المسودة.',
  'One draft at a time. Publish or discard it before asking for the next change.': 'مسودة واحدة في كل مرة. انشرها أو تجاهلها قبل أن تطلب التغيير التالي.',

  'Every publish is saved as a numbered version. Going back is instant and doesn’t use your AI allowance.': 'كل نشر يُحفظ كنسخة مرقّمة. الرجوع فوري ولا يستهلك رصيدك من الذكاء الاصطناعي.',
  'Open Storefront and find History on the right.': 'افتح «واجهة المتجر» وابحث عن «السجل» على الجانب.',
  'Pick the version you want and press Go back to this.': 'اختر النسخة التي تريدها واضغط «الرجوع إلى هذه النسخة».',
  'Confirm. Your live shop switches back within a minute.': 'أكّد. يعود متجرك المنشور إلى تلك النسخة خلال دقيقة.',
  'How far back you can go depends on your plan: 7 days on Starter up to unlimited on Partner.': 'مدى الرجوع إلى الخلف يعتمد على باقتك: من 7 أيام في Starter إلى مدة غير محدودة في Partner.',

  'Signing up builds your store for you. This is what to do next.': 'يبني التسجيل متجرك من أجلك. وهذا ما تفعله بعد ذلك.',
  'Describe your shop on the first screen. The AI builds a first version you can change later.': 'صِف متجرك في الشاشة الأولى. يبني الذكاء الاصطناعي نسخة أولى يمكنك تغييرها لاحقًا.',
  'Add your first product, or load sample products to see how things look.': 'أضف أول منتج لك، أو حمّل منتجات تجريبية لترى شكل المتجر.',
  'Connect a payment method in Settings › Payments.': 'اربط طريقة دفع من الإعدادات ‹ المدفوعات.',
  'Check your shipping charges in Settings › Shipping.': 'راجع رسوم الشحن من الإعدادات ‹ الشحن.',
  'Open your shop and place a test order.': 'افتح متجرك وأجرِ طلبًا تجريبيًا.',

  'New stores get everything in Business for 10 days. No credit card is needed to start.': 'تحصل المتاجر الجديدة على كل ما في باقة Business لمدة 10 أيام. لا حاجة إلى بطاقة ائتمان للبدء.',
  'Use any feature during the trial. Nothing is held back.': 'استخدم أي ميزة خلال الفترة التجريبية. لا شيء محجوب عنك.',
  'We remind you before the trial ends.': 'نذكّرك قبل انتهاء الفترة التجريبية.',
  'Pick a plan, or do nothing and move to Starter (Free).': 'اختر باقة، أو لا تفعل شيئًا لتنتقل إلى Starter (مجانية).',
  'On Starter, choose which 10 products stay live. Nothing else is deleted; it’s paused until you upgrade.': 'في Starter، اختر المنتجات العشرة التي تبقى منشورة. لا يُحذف أي شيء آخر، بل يُوقف مؤقتًا إلى أن تقوم بترقية باقتك.',

  'Ship a whole order at once, or part of it now and the rest later.': 'اشحن الطلب كاملًا دفعة واحدة، أو اشحن جزءًا منه الآن والباقي لاحقًا.',
  'Open Orders and pick an order marked To ship.': 'افتح «الطلبات» واختر طلبًا عليه علامة «للشحن».',
  'Tick the items going in this parcel.': 'حدّد العناصر التي ستكون في هذا الطرد.',
  'Choose the courier and add the tracking number.': 'اختر شركة الشحن وأضف رقم التتبع.',
  'Press Mark as shipped. The shopper gets an email with tracking.': 'اضغط «تحديد كمشحون». يتلقى المتسوق بريدًا إلكترونيًا يتضمن رقم التتبع.',

  'Suppliers add their own products and keep their stock up to date. They only ever see their own products and order lines.': 'يضيف الموردون منتجاتهم ويحدّثون مخزونهم. ولا يرون سوى منتجاتهم وبنود الطلبات الخاصة بهم.',
  'Go to Settings › Team and suppliers and press Invite a supplier.': 'انتقل إلى الإعدادات ‹ الفريق والموردون واضغط «دعوة مورد».',
  'Enter the supplier’s business name and their contact’s email.': 'أدخل اسم نشاط المورد والبريد الإلكتروني لجهة الاتصال لديه.',
  'Choose an access level: stock only, products and stock, or also packing their own orders.': 'اختر مستوى الوصول: المخزون فقط، أو المنتجات والمخزون، أو تجهيز طلباتهم أيضًا.',
  'Send the invitation. It stays open for 7 days.': 'أرسل الدعوة. تبقى سارية لمدة 7 أيام.',
  'Changing a supplier’s access level can take a few minutes to take effect.': 'قد يستغرق تغيير مستوى وصول المورد بضع دقائق حتى يسري.',
};

export default ar;
