// Arabic texts for the Home page: English text -> Arabic text.
// First draft written by Claude, to be reviewed by a native Arabic speaker before launch.
const ar = {
  // SEO
  'DripFunnel: Describe your shop, AI builds your store': 'DripFunnel: صِف متجرك ويبنيه الذكاء الاصطناعي',
  'Tell us what you sell and AI designs your homepage, pages, menus and product pages. Nothing goes live until you approve it. Start free.':
    'أخبرنا بما تبيعه ويصمّم الذكاء الاصطناعي صفحتك الرئيسية وصفحاتك وقوائمك وصفحات منتجاتك. لا يُنشر شيء قبل موافقتك. ابدأ مجانًا.',

  // Hero
  '700+ merchants': 'أكثر من 700 تاجر',
  'No templates': 'بلا قوالب',
  '0% fee on orders': 'عمولة 0% على الطلبات',
  'Tell Us What You Sell. We’ll Build': 'أخبرنا بما تبيعه. نحن نبني',
  'Your Store.': 'متجرك.',
  'No themes, no design skills, no code. Say what you sell and how it should feel. You get a homepage, pages, menus and product pages to check, and nothing goes live until you approve it.':
    'بلا قوالب جاهزة، ولا مهارات تصميم، ولا برمجة. قل لنا ماذا تبيع وما الإحساس الذي تريده لمتجرك. ستحصل على صفحة رئيسية وصفحات وقوائم وصفحات منتجات لتراجعها، ولا يُنشر شيء قبل موافقتك.',
  'Describe your shop': 'صِف متجرك',
  'Describe your shop…': 'صِف متجرك…',
  Try: 'جرّب',
  'Calm and earthy': 'هادئ وترابي',
  'Bestsellers first': 'الأكثر مبيعًا أولًا',
  'Our story': 'قصتنا',
  'Make it calm and earthy, with lots of white space and big photos.': 'اجعله هادئًا بألوان ترابية، مع مساحات بيضاء كثيرة وصور كبيرة.',
  'Put our bestsellers at the top of the homepage and add a gift guide page.': 'ضع منتجاتنا الأكثر مبيعًا في أعلى الصفحة الرئيسية وأضف صفحة لدليل الهدايا.',
  'Add a page telling the story of how we started in {city}, and link it from the menu.': 'أضف صفحة تحكي قصة بدايتنا في {city}، واربطها من القائمة.',
  'Starter is free forever. Paid plans start with 10 days of Business, no credit card.': 'خطة Starter مجانية دائمًا. تبدأ الخطط المدفوعة بـ 10 أيام من خطة Business دون بطاقة ائتمان.',

  // Merchants
  Merchants: 'التجار',
  '700+ merchants sell on DripFunnel': 'أكثر من 700 تاجر يبيعون عبر DripFunnel',
  'Merchant logo': 'شعار التاجر',

  // 01 How it works
  '01 — How it works': '01 — كيف يعمل',
  'Describe, preview, publish. Undo whenever you like.': 'صِف، عاين، انشر. وتراجع متى شئت.',
  'This is {store}, a sample shop in {country}. Click through the four steps.': 'هذا {store}، متجر تجريبي في {country}. تنقّل بين الخطوات الأربع.',
  Steps: 'الخطوات',
  Describe: 'صِف',
  Preview: 'عاين',
  Publish: 'انشر',
  Undo: 'تراجع',
  'Say what you sell and how it should feel.': 'قل ماذا تبيع وما الإحساس الذي تريده لمتجرك.',
  'See before and after on desktop, tablet and phone.': 'شاهد قبل وبعد على الحاسوب واللوحي والهاتف.',
  'Approve it. Your live shop changes in about a minute.': 'وافق عليه. يتغير متجرك المنشور خلال دقيقة تقريبًا.',
  'Every version is kept. Go back in one click.': 'نحتفظ بكل نسخة. ارجع إليها بنقرة واحدة.',
  'Next: {step}': 'التالي: {step}',
  'Start again': 'ابدأ من جديد',
  'What the AI designs': 'ما يصممه الذكاء الاصطناعي',
  'Colours and type': 'الألوان والخطوط',
  'The AI changes how your shop looks. It never changes your prices, stock or checkout.': 'يغيّر الذكاء الاصطناعي مظهر متجرك فقط. ولا يغيّر أسعارك أو مخزونك أو إتمام الشراء أبدًا.',
  'Preview size': 'حجم المعاينة',
  Desktop: 'الحاسوب',
  Tablet: 'الجهاز اللوحي',
  Phone: 'الهاتف',
  'Draft · not on your live site': 'مسودة · غير منشورة على متجرك',
  'Changed:': 'ما تغيّر:',
  'colours, type, homepage, menu, new page': 'الألوان والخطوط والصفحة الرئيسية والقائمة وصفحة جديدة',
  'Not touched:': 'ما لم يُمَس:',
  'products, prices, checkout': 'المنتجات والأسعار وإتمام الشراء',
  'Approve and publish': 'وافق وانشر',
  'Version 13 is live. We checked your site and it changed.': 'النسخة 13 منشورة. فحصنا موقعك ووجدنا أنه تغيّر.',
  'Before you publish': 'قبل النشر',
  'Nothing reaches shoppers until you press approve.': 'لا يصل شيء إلى المتسوقين حتى تضغط على “موافقة”.',
  'While it publishes': 'أثناء النشر',
  'Your shop stays open. Shoppers see the old version until the new one is ready.': 'يبقى متجرك مفتوحًا. يرى المتسوقون النسخة القديمة إلى أن تجهز الجديدة.',
  'If something breaks': 'إذا حدث خلل',
  'The draft stays a draft. Your live site doesn’t change.': 'تبقى المسودة مسودة، ولا يتغير موقعك المنشور.',
  History: 'السجل',
  'Calm, earthy homepage · bestsellers first': 'صفحة رئيسية هادئة بألوان ترابية · الأكثر مبيعًا أولًا',
  'New page: how we make it': 'صفحة جديدة: كيف نصنعه',
  'Free-returns note in the footer': 'ملاحظة الإرجاع المجاني في التذييل',
  'First version': 'النسخة الأولى',
  'Today, 10:42': 'اليوم، 10:42',
  'Yesterday, 16:05': 'أمس، 16:05',
  '28 Sep, 09:30': '28 سبتمبر، 09:30',
  '24 Sep, 14:12': '24 سبتمبر، 14:12',
  Live: 'مباشر',
  'Go back to this': 'الرجوع إلى هذه النسخة',
  'Version 13 is live. Pick any earlier version to go back to it.': 'النسخة 13 منشورة. اختر أي نسخة سابقة للعودة إليها.',
  'Version {v} is live again. Nothing else changed, and version 13 is still in your history.': 'النسخة {v} منشورة من جديد. لم يتغير أي شيء آخر، والنسخة 13 ما زالت في سجلك.',

  // 02 Fees
  '02 — Fees': '02 — الرسوم',
  'Read the last line of the receipt.': 'اقرأ السطر الأخير من الإيصال.',
  'DripFunnel takes nothing from your orders, on every plan, including Starter. You pay your payment provider’s own fee and that’s it.':
    'لا تأخذ DripFunnel أي عمولة من طلباتك، في جميع الخطط بما فيها Starter. تدفع فقط رسوم مزوّد الدفع الخاصة به، وهذا كل شيء.',
  Starter: 'Starter',
  'Free forever · 10 products': 'مجانية دائمًا · 10 منتجات',
  'Paid plans': 'الخطط المدفوعة',
  '10 days of Business first, no card': '10 أيام من خطة Business أولًا، دون بطاقة',
  'Changing plan': 'تغيير الخطة',
  'Upgrades now · downgrades at period end': 'الترقية فورًا · التخفيض عند نهاية الفترة',
  'See plans and prices in {currency}': 'اطّلع على الخطط والأسعار بـ {currency}',
  'Sample order receipt': 'إيصال طلب تجريبي',
  'Order #1042 · {city}': 'الطلب #1042 · {city}',
  Subtotal: 'المجموع الفرعي',
  '{tax} included': '{tax} مشمولة',
  '{tax} (sample)': '{tax} (تجريبية)',
  Delivery: 'التوصيل',
  Free: 'مجاني',
  'Payment provider': 'مزوّد الدفع',
  'Their own fee': 'رسومه الخاصة',
  'Shopper paid': 'ما دفعه المتسوق',
  'DripFunnel fee': 'عمولة DripFunnel',
  'Sample order · thank you for shopping small': 'طلب تجريبي · شكرًا لدعمك المتاجر الصغيرة',
  VAT: 'ضريبة القيمة المضافة',
  GST: 'ضريبة السلع والخدمات',
  'Sales tax': 'ضريبة المبيعات',

  // 03 What you get
  '03 — What you get': '03 — ما ستحصل عليه',
  'Everything a shop needs, in one portal.': 'كل ما يحتاجه المتجر في بوابة واحدة.',
  'AI designs your whole store': 'الذكاء الاصطناعي يصمّم متجرك بالكامل',
  'Homepage, pages, menus, product pages and the look of every one. Preview, publish, undo.': 'الصفحة الرئيسية والصفحات والقوائم وصفحات المنتجات ومظهر كل منها. عاين وانشر وتراجع.',
  'Zero fees on your orders': 'بلا رسوم على طلباتك',
  'On every plan, including Starter. You pay only your payment provider’s own fee.': 'في جميع الخطط بما فيها Starter. تدفع فقط رسوم مزوّد الدفع الخاصة به.',
  'Start free': 'ابدأ مجانًا',
  'Starter is free forever. Paid plans start with 10 days of everything in Business, no credit card.': 'خطة Starter مجانية دائمًا. تبدأ الخطط المدفوعة بـ 10 أيام من كل ما في خطة Business دون بطاقة ائتمان.',
  'A catalogue that does the detail': 'كتالوج يهتم بأدق التفاصيل',
  'Sizes and colours, A+ content, product video, size charts, collections and filters. Import from a spreadsheet or Shopify.': 'المقاسات والألوان ومحتوى A+ وفيديو المنتج وجداول المقاسات والمجموعات والفلاتر. استورد من جدول بيانات أو من Shopify.',
  'Sell in many countries': 'بِع في دول كثيرة',
  'Markets, currencies and languages, with {tax} and other local tax, duties at checkout, and local payments and couriers.': 'أسواق وعملات ولغات، مع {tax} وغيرها من الضرائب المحلية، والرسوم الجمركية عند إتمام الشراء، وطرق الدفع وشركات الشحن المحلية.',
  'Offers that bring people back': 'عروض تعيد الناس إلى متجرك',
  'Discount codes, automatic offers, buy X get Y, single-use codes and abandoned-cart reminders.': 'رموز خصم وعروض تلقائية واشترِ X واحصل على Y ورموز للاستخدام مرة واحدة وتذكيرات بالسلات المتروكة.',
  'Suppliers who manage their own shelf': 'موردون يديرون رفّهم بأنفسهم',
  'Invite suppliers to add products, keep stock up to date and even pack their own orders. Approve first if you like.': 'ادعُ الموردين لإضافة المنتجات وتحديث المخزون وحتى تجهيز طلباتهم بأنفسهم. وافق أولًا إن شئت.',
  'Your team, with the right keys': 'فريقك، بالصلاحيات المناسبة',
  'Staff accounts with Owner, Manager and Staff roles. Each sees only what their job needs.': 'حسابات للموظفين بأدوار المالك والمدير والموظف. يرى كل منهم ما تتطلبه مهمته فقط.',

  // 04 Your portal
  '04 — Your portal': '04 — بوابتك',
  'Open it and see what needs you.': 'افتحها وشاهد ما يحتاج إليك.',
  'Home starts with what’s waiting: orders to ship, carts to win back, supplier products to approve. Then today’s numbers.': 'تبدأ الصفحة الرئيسية بما ينتظرك: طلبات للشحن وسلات لاستعادتها ومنتجات موردين للموافقة عليها. ثم أرقام اليوم.',
  Orders: 'الطلبات',
  Customers: 'العملاء',
  Offers: 'العروض',
  'Abandoned carts': 'السلات المتروكة',
  Reports: 'التقارير',
  Products: 'المنتجات',
  Collections: 'المجموعات',
  Storefront: 'واجهة المتجر',
  Settings: 'الإعدادات',
  Billing: 'الفوترة',
  'Good morning, {owner}': 'صباح الخير، {owner}',
  '{store} · sample data': '{store} · بيانات تجريبية',
  'Waiting for you': 'بانتظارك',
  '4 orders to ship': '4 طلبات للشحن',
  'Oldest paid 2 hours ago': 'أقدمها مدفوع قبل ساعتين',
  Ship: 'شحن',
  '2 abandoned carts to remind': 'سلتان متروكتان للتذكير',
  'Worth {amount}': 'بقيمة {amount}',
  Remind: 'تذكير',
  '1 supplier product to approve': 'منتج واحد من مورد بانتظار الموافقة',
  'Added by your supplier this morning': 'أضافه موردك هذا الصباح',
  Review: 'مراجعة',
  'Takings today': 'مبيعات اليوم',
  'Orders today': 'طلبات اليوم',
  'Visitors today': 'زوار اليوم',
  'Open the portal': 'افتح البوابة',

  // 05 Sell worldwide
  '05 — Sell worldwide': '05 — البيع عالميًا',
  'Local rules, local payments, local couriers.': 'قواعد محلية ومدفوعات محلية وشركات شحن محلية.',
  'Your shop follows the rules of the country it sells in. Here is what changes in three of them.': 'يلتزم متجرك بقواعد البلد الذي يبيع فيه. إليك ما يتغير في ثلاثة منها.',
  'Country comparison': 'مقارنة بين الدول',
  'Your region': 'منطقتك',
  'Sample shop: {store}': 'متجر تجريبي: {store}',
  Currency: 'العملة',
  Tax: 'الضريبة',
  Payments: 'المدفوعات',
  Couriers: 'شركات الشحن',
  'Compare price': 'السعر المقارَن به',
  'Product code': 'رمز المنتج',
  'GST at 5%, included in every price': 'ضريبة السلع والخدمات 5% مشمولة في كل سعر',
  'Sales tax worked out by state and added at checkout': 'تُحسب ضريبة المبيعات حسب الولاية وتُضاف عند إتمام الشراء',
  'Cashfree, PhonePe, cash on delivery, bank transfer': 'Cashfree، PhonePe، الدفع عند الاستلام، التحويل المصرفي',
  'Stripe, PayPal': 'Stripe، PayPal',
  'Stripe, Tabby, Apple Pay, cash on delivery': 'Stripe، Tabby، Apple Pay، الدفع عند الاستلام',
  Shiprocket: 'Shiprocket',
  'Aramex, Emirates Post, DHL': 'Aramex، بريد الإمارات، DHL',
  'USPS, UPS, FedEx': 'USPS، UPS، FedEx',
  'MRP shown, and your price can never go above it': 'يُعرض السعر الأقصى للبيع بالتجزئة (MRP)، ولا يمكن أن يتجاوزه سعرك',
  'MSRP only. No made-up “was” prices': 'سعر التجزئة المقترح (MSRP) فقط. بلا أسعار “سابقة” مختلقة',
  'HSN code, required': 'رمز HSN (إلزامي)',
  'HTS code, optional': 'رمز HTS (اختياري)',

  // Placeholders
  'What merchants say': 'ماذا يقول التجار',
  'Testimonial placeholder': 'مكان رأي أحد التجار',
  '“A merchant’s own words go here, one or two sentences about what changed for their shop.”': '“هنا كلمات التاجر نفسه، جملة أو جملتان عمّا تغيّر في متجره.”',
  'Name · Shop · Country': 'الاسم · المتجر · الدولة',

  // Closing band
  'Your shop can be live today.': 'يمكن أن يصبح متجرك مباشرًا اليوم.',
  'Describe it, preview it, publish it. Starter is free forever.': 'صِفه وعاينه وانشره. خطة Starter مجانية دائمًا.',
  'Or book a demo': 'أو احجز عرضًا توضيحيًا',
};

export default ar;
