// Arabic texts for the Pricing page: English text -> Arabic text.
// First draft written by Claude, to be reviewed by a native Arabic speaker before launch.
const ar = {
  // Top of the page
  'Start free. Pay when your shop grows.': 'ابدأ مجانًا. وادفع عندما يكبر متجرك.',
  'Try everything in Business free for 10 days · no credit card required': 'جرّب كل ما في باقة Business مجانًا لمدة 10 أيام · دون الحاجة إلى بطاقة ائتمان',
  'Every plan has a real shop, unlimited orders, zero fees on your orders and the legal details your markets need. Paid plans add more products, a team, suppliers and selling abroad.':
    'كل باقة تمنحك متجرًا حقيقيًا وطلبات غير محدودة ودون أي رسوم على طلباتك، مع التفاصيل القانونية التي تحتاجها أسواقك. وتضيف الباقات المدفوعة منتجات أكثر وفريق عمل وموردين وإمكانية البيع خارج بلدك.',
  'Billing period': 'فترة الفوترة',
  Monthly: 'شهريًا',
  Yearly: 'سنويًا',
  'Save 50%': 'وفّر 50%',
  Currency: 'العملة',
  Plans: 'الباقات',

  // Plans
  'Starter (Free)': 'Starter (مجانية)',
  Growth: 'Growth',
  'Growth Pro': 'Growth Pro',
  Business: 'Business',
  Partner: 'Partner',
  'Try it with real shoppers. Free for life.': 'جرّبه مع متسوقين حقيقيين. مجاني مدى الحياة.',
  'Your first real shop, on your own domain.': 'متجرك الحقيقي الأول، على نطاقك الخاص.',
  'A small team, more markets and a richer shop.': 'فريق صغير وأسواق أكثر ومتجر أغنى.',
  'High volume, many suppliers, selling abroad.': 'حجم مبيعات كبير وموردون كثر وبيع خارج البلاد.',
  'White-label, many stores, your own terms.': 'علامة تجارية خاصة بك، ومتاجر كثيرة، وشروطك أنت.',
  'Start 10-day free trial': 'ابدأ تجربة مجانية لمدة 10 أيام',
  'Talk to us': 'تحدّث معنا',
  'Most popular': 'الأكثر شيوعًا',
  Free: 'مجاني',
  Custom: 'مخصص',
  '/month': '/شهريًا',
  'Forever. No card needed.': 'للأبد. دون الحاجة إلى بطاقة.',
  'Built around your business': 'مصمم حول احتياجات نشاطك',
  '{price} billed yearly, after 10 free days': '{price} تُدفع سنويًا، بعد 10 أيام مجانية',
  'Billed monthly, after 10 free days. {price}/month if you pay yearly.': 'تُدفع شهريًا، بعد 10 أيام مجانية. {price}/شهريًا إذا دفعت سنويًا.',
  '10 products': '10 منتجات',
  'Your shop on a DripFunnel address': 'متجرك على عنوان من DripFunnel',
  'AI designs your shop on your own AI key': 'يصمم الذكاء الاصطناعي متجرك باستخدام مفتاح الذكاء الاصطناعي الخاص بك',
  'Owner only': 'المالك فقط',
  'No fee on your orders, ever': 'لا رسوم على طلباتك، أبدًا',
  '100 products': '100 منتج',
  'Your own domain': 'نطاقك الخاص',
  '2 staff accounts': 'حسابان للموظفين',
  'Import from a spreadsheet': 'الاستيراد من جدول بيانات',
  'The 4 reports': 'التقارير الأربعة',
  '5,000 products': '5,000 منتج',
  'A+ content and video': 'محتوى A+ وفيديو',
  '5 staff accounts': '5 حسابات للموظفين',
  '2 markets, currencies and languages': 'سوقان وعملتان ولغتان',
  'AI included, no key needed': 'الذكاء الاصطناعي مشمول، دون حاجة إلى مفتاح',
  'Remove “Powered by DripFunnel”': 'إزالة عبارة «Powered by DripFunnel»',
  'Unlimited products': 'منتجات غير محدودة',
  'Suppliers with full access': 'موردون بصلاحيات كاملة',
  '15 staff accounts': '15 حسابًا للموظفين',
  '10 markets, currencies and languages': '10 أسواق و10 عملات و10 لغات',
  'Duties and import taxes at checkout': 'الرسوم الجمركية وضرائب الاستيراد عند إتمام الشراء',
  'Custom reports and priority support': 'تقارير مخصصة ودعم ذو أولوية',
  'Everything in Business': 'كل ما في باقة Business',
  'Your brand on the portal, shops and emails': 'علامتك التجارية على البوابة والمتاجر والرسائل',
  'Many stores under one account': 'متاجر كثيرة تحت حساب واحد',
  'SSO and full API access': 'تسجيل الدخول الموحد (SSO) وصول كامل إلى واجهة API',
  'Migration, onboarding and uptime guarantee': 'النقل والتهيئة وضمان التشغيل المستمر',
  'Named account manager': 'مدير حساب مخصص',
  'Optional: we build your storefront for you, {price} one-time': 'اختياري: نبني لك واجهة متجرك، {price} دفعة واحدة',
  '1 GB bandwidth a month (about 1,000–5,000 page views)': '1 جيجابايت من عرض النطاق الترددي شهريًا (نحو 1,000–5,000 مشاهدة صفحة)',
  '10 GB bandwidth a month': '10 جيجابايت من عرض النطاق الترددي شهريًا',
  '50 GB bandwidth a month': '50 جيجابايت من عرض النطاق الترددي شهريًا',
  '200 GB bandwidth a month, buy more any time': '200 جيجابايت من عرض النطاق الترددي شهريًا، ويمكنك شراء المزيد في أي وقت',
  'Bandwidth to fit your traffic': 'عرض نطاق ترددي يناسب حركة زوارك',

  // Comparison table
  'Compare every feature': 'قارن بين كل المزايا',
  'Feature comparison': 'مقارنة المزايا',
  Feature: 'الميزة',
  'Not included': 'غير مشمول',
  Included: 'مشمول',
  Catalogue: 'الكتالوج',
  'Getting started': 'البدء',
  'Getting paid': 'استلام المدفوعات',
  'Team and suppliers': 'الفريق والموردون',
  'Selling abroad': 'البيع في الخارج',
  'Shipping and stock': 'الشحن والمخزون',
  Storefront: 'واجهة المتجر',
  Reports: 'التقارير',
  'Support and partner': 'الدعم والشراكة',

  Products: 'المنتجات',
  'Photos per product': 'الصور لكل منتج',
  'Versions per product': 'الخيارات لكل منتج',
  'e.g. every size × colour': 'مثل كل مقاس × لون',
  Collections: 'المجموعات',
  'Filters and internal tags': 'عوامل التصفية والوسوم الداخلية',
  'Size charts': 'جداول المقاسات',
  'Specifications and highlights': 'المواصفات وأبرز النقاط',
  Badges: 'الشارات',
  'FAQs and related products': 'الأسئلة الشائعة والمنتجات ذات الصلة',
  'A+ content': 'محتوى A+',
  'Product video': 'فيديو المنتج',
  'Bring products from Shopify': 'انقل منتجاتك من Shopify',
  'AI for descriptions and translations': 'الذكاء الاصطناعي للأوصاف والترجمات',
  'Same AI account as your storefront: one key, or one allowance': 'حساب الذكاء الاصطناعي نفسه المستخدم لواجهة متجرك: مفتاح واحد أو رصيد واحد',
  'Legal and safety details': 'التفاصيل القانونية وتفاصيل السلامة',
  'Never behind a paywall': 'لا تُحجب أبدًا خلف اشتراك مدفوع',
  'Storefront built by our team (optional)': 'واجهة متجر يبنيها فريقنا (اختياري)',
  'Only if you want it. Or build it yourself with the AI, free on every plan': 'فقط إن أردت ذلك. أو ابنِها بنفسك بالذكاء الاصطناعي، مجانًا في كل باقة',
  '{price} one-time': '{price} دفعة واحدة',
  'DripFunnel fee on your orders': 'رسوم DripFunnel على طلباتك',
  'We never take a cut of your sales': 'لا نقتطع أي نسبة من مبيعاتك',
  'Payment gateways': 'بوابات الدفع',
  'Cash on delivery, bank transfer': 'الدفع عند الاستلام والتحويل المصرفي',
  'Discount codes and automatic offers': 'أكواد الخصم والعروض التلقائية',
  'Percent, fixed, free delivery and buy X get Y on every plan': 'نسبة مئوية ومبلغ ثابت وتوصيل مجاني واشترِ X واحصل على Y في كل باقة',
  'Customer-group offers, tiers, single-use codes': 'عروض لمجموعات العملاء ومستويات وأكواد للاستخدام مرة واحدة',
  'Offer results': 'نتائج العروض',
  'Staff accounts': 'حسابات الموظفين',
  'Manager role': 'دور المدير',
  Suppliers: 'الموردون',
  'Stock only, products and stock, or also packing their own orders': 'المخزون فقط، أو المنتجات والمخزون، أو تجهيز طلباتهم بأنفسهم أيضًا',
  'Approve supplier products': 'اعتماد منتجات الموردين',
  'Suppliers pack their own orders': 'الموردون يعبّئون طلباتهم بأنفسهم',
  Markets: 'الأسواق',
  Currencies: 'العملات',
  'Automatic conversion, or set prices yourself': 'تحويل تلقائي، أو حدّد الأسعار بنفسك',
  Languages: 'اللغات',
  'Price adjustment per market': 'تعديل السعر لكل سوق',
  'Fixed prices per market': 'أسعار ثابتة لكل سوق',
  'Own domain per market': 'نطاق خاص لكل سوق',
  'Stock locations': 'مواقع المخزون',
  'Couriers you can connect': 'شركات الشحن التي يمكنك ربطها',
  'Live courier rates at checkout': 'أسعار الشحن المباشرة عند إتمام الشراء',
  'Delivery-area lists': 'قوائم مناطق التوصيل',
  'Monthly bandwidth': 'عرض النطاق الترددي الشهري',
  'Total data your shop sends to shoppers. 1 GB usually covers 1,000–5,000 page views a month.': 'إجمالي البيانات التي يرسلها متجرك إلى المتسوقين. يكفي 1 جيجابايت عادةً لنحو 1,000–5,000 مشاهدة صفحة شهريًا.',
  'Buy extra bandwidth': 'شراء عرض نطاق ترددي إضافي',
  'Billed per extra GB, so your shop never slows down': 'تُحتسب لكل جيجابايت إضافي، فلا يتباطأ متجرك أبدًا',
  'AI that designs your whole store': 'الذكاء الاصطناعي الذي يصمم متجرك بالكامل',
  'Starter (Free) and Growth: connect your own AI account. Growth Pro and up: included': 'Starter (مجانية) وGrowth: اربط حساب الذكاء الاصطناعي الخاص بك. من Growth Pro فما فوق: مشمول',
  'Version history': 'سجل الإصدارات',
  'Abandoned-cart reminders': 'تذكيرات السلات المتروكة',
  'From Growth Pro, reminders can include a single-use discount': 'ابتداءً من Growth Pro، يمكن أن تتضمن التذكيرات خصمًا للاستخدام مرة واحدة',
  Blog: 'المدونة',
  'Home numbers': 'أرقام الصفحة الرئيسية',
  'Takings, what sold, markets, tax': 'الإيرادات والمبيعات والأسواق والضرائب',
  'Export and supplier report': 'التصدير وتقرير الموردين',
  'Custom reports': 'تقارير مخصصة',
  Support: 'الدعم',
  'Uptime guarantee': 'ضمان التشغيل المستمر',
  'White-label': 'العلامة التجارية الخاصة',
  'Many stores, one account': 'متاجر كثيرة، حساب واحد',
  'SSO and full API': 'تسجيل الدخول الموحد (SSO) وواجهة API كاملة',
  'Migration and onboarding': 'النقل والتهيئة',

  // Table values
  Unlimited: 'غير محدود',
  'Unlimited + shared blocks': 'غير محدود + كتل مشتركة',
  '50 products': '50 منتجًا',
  'Your own AI key': 'مفتاح الذكاء الاصطناعي الخاص بك',
  'Included · monthly allowance': 'مشمول · رصيد شهري',
  'Included · larger allowance': 'مشمول · رصيد أكبر',
  None: 'لا يوجد',
  All: 'الكل',
  '3 live': '3 فعّالة',
  'Unlimited · full access': 'غير محدود · صلاحيات كاملة',
  'Home only': 'السوق المحلي فقط',
  '1 GB': '1 جيجابايت',
  '10 GB': '10 جيجابايت',
  '50 GB': '50 جيجابايت',
  '200 GB': '200 جيجابايت',
  'Full white-label': 'علامة تجارية خاصة كاملة',
  '7 days': '7 أيام',
  '30 days': '30 يومًا',
  '90 days': '90 يومًا',
  '1 year': 'سنة واحدة',
  'You send · 1 per cart': 'ترسلها بنفسك · تذكير واحد لكل سلة',
  'Automatic · up to 3': 'تلقائية · حتى 3',
  Planned: 'مخطط له',
  Email: 'البريد الإلكتروني',
  Chat: 'الدردشة',
  'Priority chat and phone': 'دردشة وهاتف بأولوية',
  'Named manager': 'مدير مخصص',

  // Footnote and prices
  'Prices in Indian rupees, before GST.': 'الأسعار بالروبية الهندية، قبل ضريبة السلع والخدمات (GST).',
  'Prices in UAE dirhams, before VAT.': 'الأسعار بالدرهم الإماراتي، قبل ضريبة القيمة المضافة.',
  'Prices in US dollars, before sales tax.': 'الأسعار بالدولار الأمريكي، قبل ضريبة المبيعات.',
  'Yearly plans cost half the monthly price. We never charge a fee on your orders. Items marked “planned” aren’t in the product yet.':
    'الباقات السنوية تكلّف نصف السعر الشهري. ولا نفرض أي رسوم على طلباتك. العناصر المميزة بعبارة «مخطط له» ليست متوفرة في المنتج بعد.',

  // FAQ
  Questions: 'الأسئلة',
  'How does the 10-day free trial work?': 'كيف تعمل التجربة المجانية لمدة 10 أيام؟',
  'Every new store gets full Business access for 10 days, no credit card required. Use every feature, then pick the plan that fits. We remind you before the trial ends, and nothing you made is ever deleted.':
    'يحصل كل متجر جديد على وصول كامل إلى باقة Business لمدة 10 أيام دون الحاجة إلى بطاقة ائتمان. استخدم كل الميزات ثم اختر الباقة المناسبة. سنذكّرك قبل انتهاء التجربة، ولن يُحذف أي شيء أنشأته.',
  'Is Starter (Free) really free forever?': 'هل باقة Starter (المجانية) مجانية فعلًا للأبد؟',
  'Yes. You keep a real shop with 10 products for as long as you like. We never take a fee on your orders, on any plan.':
    'نعم. يبقى لديك متجر حقيقي بـ 10 منتجات للمدة التي تشاء. ولا نأخذ أي رسوم على طلباتك في أي باقة.',
  'What happens if I go over a limit?': 'ماذا يحدث إذا تجاوزت حدًّا ما؟',
  'Nothing breaks and nothing is deleted. Everything you have keeps selling; you just can’t add more until you move up a plan.':
    'لا يتعطل شيء ولا يُحذف شيء. يستمر بيع كل ما لديك، ولا يمكنك فقط إضافة المزيد حتى تنتقل إلى باقة أعلى.',
  'Can I change plans any time?': 'هل يمكنني تغيير الباقة في أي وقت؟',
  'Upgrades start straight away and you pay the difference for the month. Downgrades take effect at the end of your billing period.':
    'تبدأ الترقية فورًا وتدفع الفرق عن الشهر. أما التخفيض فيسري في نهاية فترة الفوترة.',
  'If I downgrade, do I lose my A+ content?': 'إذا خفّضت باقتي، هل أفقد محتوى A+؟',
  'You keep it. It’s hidden from your shop until you upgrade again, then it comes straight back.':
    'يبقى محفوظًا لديك. يُخفى عن متجرك إلى أن تقوم بالترقية مجددًا، ثم يعود فورًا.',
  'What does “your own AI key” mean?': 'ماذا يعني “مفتاح الذكاء الاصطناعي الخاص بك”؟',
  'On Starter (Free) and Growth you connect your own AI account (for example OpenAI or Anthropic) and pay them directly for what you use. It designs your store and writes product descriptions and translations. From Growth Pro, all of that AI is included with one monthly allowance: no key, no extra bill.':
    'في Starter (المجانية) وGrowth تربط حساب الذكاء الاصطناعي الخاص بك (مثل OpenAI أو Anthropic) وتدفع لهم مباشرة مقابل ما تستخدمه. يصمم متجرك ويكتب أوصاف المنتجات والترجمات. ابتداءً من Growth Pro يكون كل ذلك مشمولًا برصيد شهري واحد: دون مفتاح ودون فاتورة إضافية.',
  'What happens when I run out of AI allowance?': 'ماذا يحدث عندما ينفد رصيد الذكاء الاصطناعي؟',
  'Your shop keeps working and nothing you published changes. You can wait for next month’s allowance, move up a plan, or connect your own key to keep going.':
    'يستمر متجرك في العمل ولا يتغير أي شيء نشرته. يمكنك انتظار رصيد الشهر القادم، أو الانتقال إلى باقة أعلى، أو ربط مفتاحك الخاص لتواصل العمل.',
  'What is bandwidth, and what if I go over?': 'ما هو عرض النطاق الترددي، وماذا لو تجاوزته؟',
  'It’s the total data your shop sends to shoppers each month: pages, photos and videos. 1 GB usually covers 1,000–5,000 page views. If you go over, your shop stays online: we tell you at 80% and 100%, and you can move up a plan. On Business you can also buy extra bandwidth, billed per GB. We never switch your shop off without warning.':
    'هو إجمالي البيانات التي يرسلها متجرك إلى المتسوقين كل شهر: الصفحات والصور ومقاطع الفيديو. يكفي 1 جيجابايت عادةً لنحو 1,000–5,000 مشاهدة صفحة. وإذا تجاوزته يبقى متجرك متاحًا: نُبلغك عند 80% وعند 100%، ويمكنك الانتقال إلى باقة أعلى. وفي Business يمكنك أيضًا شراء عرض نطاق إضافي يُحتسب لكل جيجابايت. ولا نوقف متجرك أبدًا دون إنذار.',
  'Do I have to pay for storefront setup?': 'هل يجب أن أدفع مقابل إعداد واجهة المتجر؟',
  'No. The AI builds your storefront for free on every plan. Need help building your storefront? We’ll do it for you: our team builds your homepage, pages, menus and first products so you launch looking finished. It’s optional and paid once: {setup}.':
    'لا. يبني الذكاء الاصطناعي واجهة متجرك مجانًا في كل باقة. هل تحتاج إلى مساعدة في بنائها؟ سنقوم بذلك نيابةً عنك: يبني فريقنا صفحتك الرئيسية وصفحاتك وقوائمك وأول منتجاتك لتنطلق بمظهر مكتمل. وهي خدمة اختيارية تُدفع مرة واحدة: {setup}.',
  '{a} on Growth, {b} on Growth Pro, {c} on Business': '{a} في Growth، و{b} في Growth Pro، و{c} في Business',
  'Do you charge per staff member?': 'هل تحتسبون رسومًا عن كل موظف؟',
  'No. Each plan includes a number of staff accounts. Your suppliers’ users don’t count towards it.':
    'لا. تتضمن كل باقة عددًا من حسابات الموظفين. ولا يُحتسب مستخدمو مورديك ضمن هذا العدد.',
  'What does white-label mean?': 'ماذا تعني العلامة التجارية الخاصة (white-label)؟',
  'On Partner, the portal, the shops and every email carry your brand, not ours. It’s for agencies and groups running shops for others.':
    'في باقة Partner تحمل البوابة والمتاجر وكل رسالة بريد إلكتروني علامتك التجارية أنت وليس علامتنا. وهي مخصصة للوكالات والمجموعات التي تدير متاجر لصالح الآخرين.',

  // Bottom band
  'Your shop can be live today.': 'يمكن أن يصبح متجرك مباشرًا اليوم.',
  'Try everything in Business free for 10 days. No credit card required.': 'جرّب كل ما في باقة Business مجانًا لمدة 10 أيام. دون الحاجة إلى بطاقة ائتمان.',

  // SEO
  'See plans and prices in your currency. Starter is free forever, and paid plans start with a 10-day trial.': 'اطّلع على الباقات والأسعار بعملتك. باقة Starter مجانية للأبد، وتبدأ الباقات المدفوعة بتجربة لمدة 10 أيام.',
};

export default ar;
