// Arabic texts for the header, footer and banner: English text -> Arabic text.
// First draft written by Claude, to be reviewed by a native Arabic speaker before launch.
const ar = {
  'Skip to content': 'انتقل إلى المحتوى',
  'DripFunnel home': 'الصفحة الرئيسية لـ DripFunnel',
  Main: 'التنقل الرئيسي',
  Home: 'الرئيسية',
  Features: 'المزايا',
  'AI Builder': 'منشئ المتاجر بالذكاء الاصطناعي',
  Pricing: 'الأسعار',
  Partners: 'الشركاء',
  Resources: 'المصادر',
  Blog: 'المدونة',
  'Help centre': 'مركز المساعدة',
  'Contact and demo': 'تواصل معنا واحجز عرضًا',
  'Guides for running and growing a shop': 'أدلة لإدارة متجرك وتنميته',
  'How-to articles and support': 'مقالات إرشادية ودعم',
  'Talk to sales or book a demo': 'تحدث إلى المبيعات أو احجز عرضًا توضيحيًا',
  'Sign in': 'تسجيل الدخول',
  'Start free': 'ابدأ مجانًا',
  Menu: 'القائمة',
  'Switch to dark mode': 'التبديل إلى الوضع الداكن',
  'Switch to light mode': 'التبديل إلى الوضع الفاتح',
  'Describe your business and AI builds your whole store. Then run catalogue, orders, offers, suppliers and selling abroad from one portal.':
    'صِف نشاطك التجاري وسيبني الذكاء الاصطناعي متجرك بالكامل. ثم أدِر الكتالوج والطلبات والعروض والموردين والبيع خارج بلدك من بوابة واحدة.',
  'Show prices in': 'عرض الأسعار بـ',
  Language: 'اللغة',
  'Region and language': 'المنطقة واللغة',
  India: 'الهند',
  'United States': 'الولايات المتحدة',
  'United Arab Emirates': 'الإمارات العربية المتحدة',
  'India (INR)': 'الهند (INR)',
  'United States (USD)': 'الولايات المتحدة (USD)',
  'United Arab Emirates (AED)': 'الإمارات العربية المتحدة (AED)',
  Product: 'المنتج',
  Company: 'الشركة',
  Legal: 'قانوني',
  'Contact support': 'تواصل مع الدعم',
  'Book a demo': 'احجز عرضًا توضيحيًا',
  'Talk to sales': 'تحدث إلى المبيعات',
  'Become a partner': 'كن شريكًا',
  'Terms of Service': 'شروط الخدمة',
  'Privacy Policy': 'سياسة الخصوصية',
  '© 2026 DripFunnel. A Softobotics company.': '© 2026 DripFunnel. إحدى شركات Softobotics.',
  'View this page in Arabic?': 'هل تريد عرض هذه الصفحة بالعربية؟',
  'Yes, switch': 'نعم، بدّل',
  'No thanks': 'لا، شكرًا',
};

export default ar;
